// utils/notificationGenerator.js
// Create this file to fix the server error

let notificationId = 1;
let notifications = [];

const generateFleetNotifications = (io) => {
  const notificationTemplates = [
    { message: "Driver {driver} completed transport to {destination}", type: "success" },
    { message: "Vehicle maintenance scheduled for {vehicle}", type: "warning" },
    { message: "Driver {driver} is en route to {destination}", type: "info" },
    { message: "New shuttle request from {origin} to {destination}", type: "info" },
    { message: "Driver {driver} completed VIP transport for executive meeting", type: "success" },
    { message: "Traffic alert: {road} experiencing delays", type: "warning" },
    { message: "Scheduled maintenance completed on {vehicle}", type: "success" },
    { message: "Urgent: Field team requesting transport to {destination}", type: "urgent" }
  ];

  const drivers = ["James Banda", "Grace Mbewe", "Peter Phiri", "Mary Gondwe", "Thomas Jere"];
  const vehicles = [
    "Toyota Hilux (MW-001-ABC)", "Toyota Hiace (MW-002-DEF)", "Mitsubishi Pajero (MW-003-GHI)", 
    "Nissan NV350 (MW-004-JKL)", "Toyota Land Cruiser (MW-005-MNO)"
  ];
  const destinations = [
    "Lilongwe City Center", "Chileka International Airport", "Blantyre", "Zomba", 
    "Mzuzu", "Karonga", "Mulanje Mountain"
  ];
  const roads = [
    "M1 near Liwonde", "A1 highway", "Lilongwe-Salima road", 
    "Blantyre-Chiradzulu road"
  ];

  const interval = setInterval(() => {
    try {
      const template = notificationTemplates[Math.floor(Math.random() * notificationTemplates.length)];
      let message = template.message;

      // Replace placeholders
      message = message.replace('{driver}', drivers[Math.floor(Math.random() * drivers.length)]);
      message = message.replace('{vehicle}', vehicles[Math.floor(Math.random() * vehicles.length)]);
      message = message.replace('{destination}', destinations[Math.floor(Math.random() * destinations.length)]);
      message = message.replace('{origin}', destinations[Math.floor(Math.random() * destinations.length)]);
      message = message.replace('{road}', roads[Math.floor(Math.random() * roads.length)]);

      const notification = {
        id: notificationId++,
        message,
        type: template.type,
        priority: template.type === 'urgent' ? 'high' : 'normal',
        timestamp: new Date(),
        read: false,
        autoGenerated: true
      };

      notifications.push(notification);

      // Keep only last 100 notifications
      if (notifications.length > 100) {
        notifications = notifications.slice(-100);
      }

      // Emit real-time notification
      if (io) {
        io.emit('new-notification', notification);
      }
      
      console.log(`[Fleet Notification] ${notification.type.toUpperCase()}: ${notification.message}`);
      
    } catch (error) {
      console.error('Error generating fleet notification:', error);
    }
    
  }, Math.random() * 12000 + 8000); // Random interval between 8-20 seconds

  console.log('Fleet notification generator started');
  return interval;
};

const stopFleetNotifications = (interval) => {
  if (interval) {
    clearInterval(interval);
    console.log('Fleet notification generator stopped');
  }
};

const getStoredNotifications = () => {
  return notifications;
};

const addNotification = (notification) => {
  notifications.push({
    ...notification,
    id: notificationId++,
    timestamp: new Date()
  });
  
  if (notifications.length > 100) {
    notifications = notifications.slice(-100);
  }
};

module.exports = {
  generateFleetNotifications,
  stopFleetNotifications,
  getStoredNotifications,
  addNotification
};